<a href="https://colab.research.google.com/github/umasrid/DAE-PROGRAM/blob/main/slicing_of_1d%2C2d%2C3d_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np
arr=np.array([10,20,30,40,50,60,70,80,90,100])
print("ORIGINAL ARRAY: ",arr)
print("First 4 elements:",arr[:5])
print("Elements from 2 to 5:",arr[2:6])
print("Every second elements:",arr[::2])
print("Last 3 elements:",arr[-3:])
print("Every 2*2 elements:",arr[::2*2])

ORIGINAL ARRAY:  [ 10  20  30  40  50  60  70  80  90 100]
First 4 elements: [10 20 30 40 50]
Elements from 2 to 5: [30 40 50 60]
Every second elements: [10 30 50 70 90]
Last 3 elements: [ 80  90 100]
Every 2*2 elements: [10 50 90]


In [7]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print("ORIGINAL ARRAY: ",arr)
print("First Row: ",arr[0])
print("Second Column: ",arr[:,1])
print("First Two Rows And First Three Columns: ",arr[:2,:2])
print("Last Two Rows: ",arr[-2:,:])



ORIGINAL ARRAY:  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
First Row:  [1 2 3]
Second Column:  [ 2  5  8 11 14]
First Two Rows And First Three Columns:  [[1 2]
 [4 5]]
Last Two Rows:  [[10 11 12]
 [13 14 15]]


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr[0:3,1:2])

[[2]
 [5]
 [8]]


In [12]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
print("Original 3-D Arrary:",arr)
print("First 2-D Array:",arr[0])
print("Second Row Of First 2-D Array:",arr[0,1])
print("first two elements:",arr[0,1,:2])
print("All First Columns:",arr[:,:,0])

Original 3-D Arrary: [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
First 2-D Array: [[1 2 3]
 [4 5 6]]
Second Row Of First 2-D Array: [4 5 6]
first two elements: [4 5]
All First Columns: [[ 1  4]
 [ 7 10]
 [13 16]]


In [13]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[-4:-1])

[7 8 9]


In [14]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::-1]) #Reverse of the array
print(arr[-3:])  #Last three elements
print(arr[:-2])

[10  9  8  7  6  5  4  3  2  1]
[ 8  9 10]
[1 2 3 4 5 6 7 8]
