<a href="https://colab.research.google.com/github/umasrid/ADE-PROGRAM/blob/main/week%201(arrays%20using%20numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [28]:
import numpy as np
random_arr = np.random.rand(4,4)
print(random_arr)

[[0.15683753 0.40920098 0.34010627 0.37298062]
 [0.64466492 0.60955805 0.62090063 0.56100629]
 [0.50394412 0.37355324 0.80067908 0.87234626]
 [0.42243385 0.33014704 0.312971   0.63824667]]


In [29]:
import numpy as np
arr = np.ones((3,3),dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [30]:
arr = np.ones((5,5),dtype=int)
print(arr*12)

[[12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]
 [12 12 12 12 12]]


In [31]:
arr = np.ones((3,6))
print(arr*3)

[[3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3.]]


In [32]:
arr=np.random.randint(1,10,size=(4,6))
print(arr)

[[8 3 2 4 8 8]
 [7 9 5 4 2 7]
 [9 4 9 4 4 3]
 [9 9 7 1 6 1]]


In [34]:
arr=np.random.randn(5,3)
print(arr)

[[-0.28045953 -0.49792014  0.75323065]
 [ 1.64043144 -1.44747533  0.07396225]
 [ 0.66995165  0.07756507  0.63307221]
 [ 1.88301188  2.84226068  0.55135389]
 [-0.42804162 -0.21081924 -0.62706197]]


In [36]:
student_marks=np.array([86,95,82,69,99])
print("student_marks:")
print(student_marks)

student_marks:
[86 95 82 69 99]
